name: Gerar APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Instalar plataforma Android do Capacitor
        run: npm install @capacitor/android@^7.4.3

      - name: Baixar Bíblia para funcionamento offline
        run: |
          curl -L --fail --retry 3 \
            -o public/bible.json \
            https://raw.githubusercontent.com/midvash/bible-data/main/versions/pt/almeida-livre/almeida-livre.json

      - name: Criar versão web
        run: npm run build

      - name: Criar projeto Android
        run: npx cap add android

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Aceitar licenças do Android
        run: yes | sdkmanager --licenses > /dev/null || true

      - name: Instalar Android SDK
        run: |
          sdkmanager "pl
