name: Gerar APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Baixar Bíblia
        run: |
          curl -L --fail --retry 3 \
          -o public/bible.json \
          https://raw.githubusercontent.com/midvash/bible-data/main/versions/pt/almeida-livre/almeida-livre.json

      - name: Compilar aplicação
        run: npm run build

      - name: Criar projeto Android
        run: npx cap add android

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Instalar SDK Android
        run: |
          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager 'platform-tools' 'platforms;android-35' 'build-tools;35.0.0'

      - name: Gerar APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Biblia-Sagrada-Devocional-Lite-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
